### PR TITLE
286 Fix PR: Change NUnit v2 to v3

### PR DESCRIPTION
**Pull request by savornicesei**
Most of the tests work but there are differences between number of failed tests in VS2019 and from build script.

L.E: The number of changed files is correct. Not sure why the older commits appear on PR; probably from the initial PR merge ( #259 )

### CODE REVIEW

**Comment by mintsoft** [comment]
@savornicesei have you rebased the branch based on master as it stands right now? It kinda looks like it hasn't got a consistent history vs the master branch

**Comment by savornicesei** [comment]
@mintsoft Did an interactive rebase to get rid of the unwanted commits.

**Comment by mintsoft** [comment]
Just FYI I'm trying build this up on Win10 + VS 2019 and I'm getting some minor DLL hell issues: 
` C:\code\CruiseControl.NET\project\WebDashboard\WebDashboard.csproj(933,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v11.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.`

IIRC this is all due to webdeploy references in the WebDashboard; presumably you're not seeing this yourself? I'll keep digging and see what shows up

**Comment by savornicesei** [comment]
@mintsoft I'm not getting any error but I do have:

- 4.0 Tools from 4.0 SDK installed (the SDK installer does not work but if you mount the SDK.iso, you can run the tools installer)

- _ASP.NET and web development tools_ and _ASP.NET MVC 4_ installed from VS2019 installer

From the error message you get seems that the $(VSToolsPath) is wrong. On my machine it points to C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0
Let me know If it still doesn't work after installing the 2 ASP.NET components from VS2019 installer.

**Comment by mintsoft** [comment]
@savornicesei Thanks for that, all building successfully now! 

I had the ASP.NET and web development tools installed, but not the "Web Development Tools plus .NET Core 2.1" which seemed to resolve it and is _obviously_ different!

**Comment by savornicesei** [comment]
Hi @mintsoft 
Any feedback on the PR?

**Comment by mintsoft** [comment]
@savornicesei  All I can say is it works! LGTM, however I've not looked over all tests thorougholy

**Comment by savornicesei** [comment]
Hi @mintsoft, @RubenWillems 
Can this PR be merged? OR do I need to do additional changes to it?

Thanks,
Simo

**Comment by RubenWillems** [comment]
Hi Simona

I've sent you an invitation to join the team.

The PR can be merged, I'm just thinking of the merge options :
° create a merge commit
° squash and merge

I'm leaning to 'squash and merge' to be sure that there is no problem with
the history, I'm no Git guru.

If you accept the invitation, you may merge it yourself offcourse, that way
you can immediately test if you have the proper rights.


with kind regards
Ruben Willems

**Comment by savornicesei** [comment]
Hi @RubenWillems 
For this PR I would go for 'merge commit' or 'rebase and merge' - thus the individual commits forming the PR will be preserved on the master branch.
I don't have write access so I can't merge this PR.

Best,
Simo

**Comment by RubenWillems** [comment]
Hi

I made a new team : CCNet Core with read and write access.
and you're now member of it ;-)

This should give you the rights to merge the pull request.
Can you give it a shot?

with kind regards
Ruben Willems

**Pull request merged**
