### PR TITLE
NMock to Moq migration

### PR DESCRIPTION
**Pull request by pos777**
NMock to Moq migration.
Related to https://github.com/ccnet/CruiseControl.NET/issues/264

### CODE REVIEW

**Comment by RubenWillems** [comment]
many thanks for converting all those tests to MOQ

**Comment by pos777** [comment]
Welcome! =)

**Comment by savornicesei** [comment]
@RubenWillems  Perhaps we should add this PR to the done column on 1.9 board?

**Comment by RubenWillems** [comment]
it is now on the done board ;-)

**Pull request merged**
