### PR TITLE
#265 Installer does not run from unicode folder

### PR DESCRIPTION
**Pull request by savornicesei**
- update NSIS to v3.05
- added Unicode attribute to NSIS scripts

### CODE REVIEW

**Comment by savornicesei** [comment]
Hi @RubenWillems , @mintsoft 
Any ideeas why makensis fails in AppVeyour? Locally it buit fine and I could test the installers.

**Comment by RubenWillems** [comment]
Hi

it also works on my pc, so I can not simulate the problem :-(
but from the errormessage : Unable to start child process, error 0x2

it seems that nsis itself is broken.
what I think is the problem : a dependent dll that is not available on
appveyor

I have VS installed, and I guess you have to, on the appveyor I do not
think that Vs is installed.
So to test this theory, set up a new virtual machine with only the sdk
installed, and try to run nsis from that one.

otherwise, maye hack in a new 'build' script section, that just calls the
makensis.exe without any arguments,
and see if that works. it should not crash.

that is the only way I can see to track down the problem.


with kind regards
Ruben Willems

**Comment by savornicesei** [comment]
@RubenWillems 
I've been looking into it this morning and did the following changes to the build process:
- get NSIS from chocolately in AppVeyour
- call makensis from Program Files (x86)
- pass the version as parameter to makensis (I also removed the .template from install scripts names)

I have now another weird error
```
packageCCTray:

     [exec] Starting 'C:\Program Files (x86)\NSIS\makensis.exe (/DVERSION=1.9.0.1 /V2 "D:\CruiseControl.NET\install\cctray.nsi")' in 'D:\CruiseControl.NET'
     [exec] Command line defined: "VERSION=1.9.0.1"
     [exec] Error while loading icon from "project\CCTrayLib\ResourceIcons\Green.ico": can't open file
     [exec] Error in macro MUI_INTERFACE on macroline 85
     [exec] Error in macro MUI_PAGE_INIT on macroline 6
     [exec] Error in macro MUI_PAGE_WELCOME on macroline 5
     [exec] Error in script "D:\CruiseControl.NET\install\cctray.nsi" on line 37 -- aborting creation process
```
but at least the packaging process is more straightforward. 😆

**Comment by RubenWillems** [comment]
Hi

that will probably be a path error
calling nsis from program files and the resources on other paths.

Maybe you can set a working folder for the nsis executable


grts
Ruben Willems

**Comment by savornicesei** [comment]
Thanks @RubenWillems  Your observation put me on the right track. This is ready for review.

**Comment by RubenWillems** [comment]
glad I could help ;-)

**Comment by savornicesei** [comment]
@RubenWillems  @mintsoft 
Could you review this ticket when you have some spare time?

Thank you.

**Comment by RubenWillems** [comment]
Hi

looks ok to me.

you can merge it ;-)


grts
Ruben Willems

**Comment by savornicesei** [comment]
@RubenWillems Thanks for the green light!

**Pull request merged**
